"""Mapping from common company names to NSE symbols for broker reco parsing."""

COMPANY_ALIASES = {
    "reliance industries": "RELIANCE",
    "reliance": "RELIANCE",
    "tcs": "TCS",
    "tata consultancy services": "TCS",
    "infosys": "INFY",
    "hdfc bank": "HDFCBANK",
    "icici bank": "ICICIBANK",
    "hindustan unilever": "HINDUNILVR",
    "hul": "HINDUNILVR",
    "state bank of india": "SBIN",
    "sbi": "SBIN",
    "bharti airtel": "BHARTIARTL",
    "itc": "ITC",
    "kotak mahindra bank": "KOTAKBANK",
    "axis bank": "AXISBANK",
    "larsen & toubro": "LT",
    "l&t": "LT",
    "bajaj finance": "BAJFINANCE",
    "asian paints": "ASIANPAINT",
    "hcl technologies": "HCLTECH",
    "hcl tech": "HCLTECH",
    "maruti suzuki": "MARUTI",
    "sun pharmaceutical": "SUNPHARMA",
    "sun pharma": "SUNPHARMA",
    "titan": "TITAN",
    "ultratech cement": "ULTRACEMCO",
    "nestle india": "NESTLEIND",
    "wipro": "WIPRO",
    "mahindra & mahindra": "M&M",
    "power grid": "POWERGRID",
    "powergrid": "POWERGRID",
    "ntpc": "NTPC",
    "adani enterprises": "ADANIENT",
    "adani ports": "ADANIPORTS",
    "coal india": "COALINDIA",
    "bajaj finserv": "BAJAJFINSV",
    "tata motors": "TATAMOTORS",
    "hindalco": "HINDALCO",
    "hindalco industries": "HINDALCO",
    "ongc": "ONGC",
    "oil & natural gas": "ONGC",
    "jsw steel": "JSWSTEEL",
    "tata steel": "TATASTEEL",
    "bpcl": "BPCL",
    "bharat petroleum": "BPCL",
    "ioc": "IOC",
    "indian oil": "IOC",
    "grasim": "GRASIM",
    "cipla": "CIPLA",
    "divi's laboratories": "DIVISLAB",
    "dr reddy's": "DRREDDY",
    "dr reddys": "DRREDDY",
    "eicher motors": "EICHERMOT",
    "hero motocorp": "HEROMOTOCO",
    "apollo hospitals": "APOLLOHOSP",
    "britannia": "BRITANNIA",
    "tata consumer": "TATACONSUM",
    "tata consumer products": "TATACONSUM",
    "upl": "UPL",
    "indusind bank": "INDUSINDBK",
    "tech mahindra": "TECHM",
    "hdfc life": "HDFCLIFE",
    "sbi life": "SBILIFE",
    "shree cement": "SHREECEM",
    "acc": "ACC",
    "ambuja cements": "AMBUJACEM",
    "aurobindo pharma": "AUROPHARMA",
    "bandhan bank": "BANDHANBNK",
    "bank of baroda": "BANKBARODA",
    "bank of india": "BANKINDIA",
    "bel": "BEL",
    "bharat electronics": "BEL",
    "bhel": "BHEL",
    "bharat heavy electricals": "BHEL",
    "biocon": "BIOCON",
    "bosch": "BOSCHLTD",
    "canara bank": "CANBK",
    "cholamandalam finance": "CHOLAFIN",
    "colgate palmolive": "COLPAL",
    "concor": "CONCOR",
    "coromandel international": "COROMANDEL",
    "cummins india": "CUMMINSIND",
    "dabur": "DABUR",
    "dlf": "DLF",
    "escorts": "ESCORTS",
    "exide industries": "EXIDEIND",
    "federal bank": "FEDERALBNK",
    "gail": "GAIL",
    "glenmark": "GLENMARK",
    "godrej consumer": "GODREJCP",
    "godrej properties": "GODREJPROP",
    "hal": "HAL",
    "hindustan aeronautics": "HAL",
    "havells": "HAVELLS",
    "hdfc amc": "HDFCAMC",
    "hindustan petroleum": "HINDPETRO",
    "honeywell automation": "HONAUT",
    "idfc first bank": "IDFCFIRSTB",
    "indian hotels": "INDHOTEL",
    "interglobe aviation": "INDIGO",
    "indigo": "INDIGO",
    "irctc": "IRCTC",
    "jindal steel": "JINDALSTEL",
    "jubilant foodworks": "JUBLFOOD",
    "ltimindtree": "LTIM",
    "lupin": "LUPIN",
    "manappuram finance": "MANAPPURAM",
    "marico": "MARICO",
    "max financial": "MFSL",
    "mahanagar gas": "MGL",
    "mphasis": "MPHASIS",
    "mrf": "MRF",
    "navin fluorine": "NAVINFLUOR",
    "nmdc": "NMDC",
    "oracle financial": "OFSS",
    "piramal enterprises": "PEL",
    "persistent systems": "PERSISTENT",
    "petronet lng": "PETRONET",
    "pfc": "PFC",
    "power finance": "PFC",
    "pidilite": "PIDILITIND",
    "pi industries": "PIIND",
    "pnb": "PNB",
    "punjab national bank": "PNB",
    "polycab": "POLYCAB",
    "rbl bank": "RBLBANK",
    "sail": "SAIL",
    "siemens": "SIEMENS",
    "srf": "SRF",
    "tata chemicals": "TATACHEM",
    "tata communications": "TATACOMM",
    "tata elxsi": "TATAELXSI",
    "tata power": "TATAPOWER",
    "torrent pharma": "TORNTPHARM",
    "trent": "TRENT",
    "tvs motor": "TVSMOTOR",
    "vedanta": "VEDL",
    "voltas": "VOLTAS",
    "zydus lifesciences": "ZYDUSLIFE",
    "ashok leyland": "ASHOKLEY",
    "berge paint": "BERGEPAINT",
    "bharat forge": "BHARATFORG",
    "dalmiabharat": "DALBHARAT",
    "deepak nitrite": "DEEPAKNTR",
    "dixon technologies": "DIXON",
    "gmr infrastructure": "GMRINFRA",
    "gujarat gas": "GUJGASLTD",
    "indus towers": "INDUSTOWER",
    "lic housing finance": "LICHSGFIN",
}


def resolve_symbol(text: str) -> str:
    """Best-effort company-name to symbol resolution."""
    normalized = text.lower().strip()
    # Direct alias match
    if normalized in COMPANY_ALIASES:
        return COMPANY_ALIASES[normalized]
    # Remove common suffixes
    for suffix in [" ltd", " limited", " industries", " corporation", " company", " group", " bank"]:
        if normalized.endswith(suffix):
            trimmed = normalized[: -len(suffix)].strip()
            if trimmed in COMPANY_ALIASES:
                return COMPANY_ALIASES[trimmed]
    return ""
